### ISSUE TITLE
Not available the setOnProgressListener

### ISSUE THREAD

**Issue by abbasnaqdi** [alxrm/audiowave-progressbar#11]
Hi, thank you for your good library.
I'm having a problem, I added AudioWaveView and working properly, but unfortunately, setOnProgressListener is not found for me.

In fact, this interface does not exist. Please check and correct. Thank .

**Comment by alxrm** [comment]
Hey @okabbas, thanks for your reply, let me please check if the sample activity still works. 

Whilst you may want to try to Clean+Build, if you haven't tried it yet, and check whether the issue persists or not.

**Comment by abbasnaqdi** [comment]
Hello . The sample project does not work for me.
I also did the Clean + ReBuild operation, but still the problem is going wrong and I get the error below.

> Error:(145, 37) Unresolved reference: setOnProgressListener

my code 

```
        holder.itemView.wave_voice.setOnProgressListener(object : OnProgressListener {
            override fun onStartTracking(progress: Float) {
                //
            }
            override fun onStopTracking(progress: Float) {
                //
            }
            override fun onProgressChanged(progress: Float, byUser: Boolean) {
                //
            }
        });

        Observable.fromCallable {
            filebyte = getFileByte(context, voice.file)
        }.observeOn(Schedulers.newThread()).subscribeOn(AndroidSchedulers.mainThread())
                .subscribe {
                    holder.itemView.wave_voice.setRawData(filebyte)
                    holder.itemView.wave_voice.scaledData = filebyte
                }
```

I checked your code and found that the setOnProgressListener interface did not exist at all.

**Comment by alxrm** [comment]
@okabbas woah, that's really odd, since the repository shows it's presence, give me just a bit more time, I need to update the dependencies, since I haven't touched this in a while

**Comment by alxrm** [comment]
@okabbas you're trying to use Java API here, you see, with kotlin you need to use _properties_ like this:

```kotlin
    wave.onProgressListener = object : OnProgressListener {
      override fun onProgressChanged(progress: Float, byUser: Boolean) {
        TODO()
      }

      override fun onStartTracking(progress: Float) {
        TODO()
      }

      override fun onStopTracking(progress: Float) {
        TODO()
      }
    }
```

**Comment by alxrm** [comment]
@okabbas or there are some properties for your convenience, check those out:

```kotlin
    wave.onStopTracking = {
      Log.e("wave", "Progress set: $it")
    }
    
    wave.onStartTracking = {
      Log.e("wave", "Started tracking from: $it")
    }

    wave.onProgressChanged = {progress, byUser ->
      Log.e("wave", "Progress set: $progress, and it's $byUser that user did this")
    }

```

**Comment by abbasnaqdi** [comment]
Oh my God :) It did 
I did not know that. Thank you so much 
Please add this code in readme file For people who might make me wrong.
Thanks for your quick response and good support

**Comment by alxrm** [comment]
@okabbas glad to help, and I'm closing this issue since the problem's solved. Gonna update the readme in a few minutes.
