### ISSUE TITLE
can i make as flat

### ISSUE THREAD

**Issue by nzala** [alxrm/audiowave-progressbar#2]
i mean like LED- or LCD-like bar gauge control for iOS
https://github.com/ChiefPilot/F3BarGauge
[https://github.com/ChiefPilot/F3BarGauge](url)

listen audiowave progressbar

**Comment by alxrm** [comment]
Make `minChunkHeight` equal to element `height`, that'll do the trick.

**Comment by nzala** [comment]
i also want make waveColor in gradient Color
and can it take the input from the  audio Source MIC(device)

**Comment by alxrm** [comment]
Unfortunately you cannot have it in gradient color.

If the input is a file, you can read it to array of bytes and use.

**Comment by nzala** [comment]
i mean the input from the audio Source MIC(device)

**Comment by alxrm** [comment]
Sure why not
