### ISSUE TITLE
  error: resource style/LyTheme (aka myapp:style/LyTheme) not found.

### ISSUE THREAD

**Issue by Akshshr** [alxrm/audiowave-progressbar#24]
Title says it all! 

Otherwise really cool library! looking forward in using it. 

This happens right after pasting the dependency

**Comment by alxrm** [comment]
Weird, idk man, seems like a attribute name conflict or something, can't help you without knowing more about the issue

**Comment by Akshshr** [comment]
Sorry about this, just my android studio acting up, cause logic!
