### ISSUE TITLE
AudioWaveView inside ScrollView

### ISSUE THREAD

**Issue by anugotta** [alxrm/audiowave-progressbar#25]
Hey @alxrm , Thanks for this library. but i have a query. Right now i think the width of Audiowaves are confined to the width of parent layout. i want to add it inside a scrollview so that it takes as much width it needs and i should be able to scroll. is there an easy way to do this or need to modify the library code?

**Comment by alxrm** [comment]
Hey @anugotta, thanks for a kind word, but unfortunately there's no way to do it currently, so you either have to fork this library or find some other library (there are plenty of better ones)

**Comment by anugotta** [comment]
Okay...i will fork this one! Thanks.
