### ISSUE TITLE
Don't know to convert to data type to use setRawwData() function

### ISSUE THREAD

**Issue by lhtriet** [alxrm/audiowave-progressbar#26]
I figured out that this lib only supports .wav, but when we use a correct param, we can also draw the wave. 
But the dataType I receive from server is a JSON like: "["0.01", "0.03", "0.02",....]" and I cannot convert to ByteArray type that the function need. Do we need to do any further step, since I can convert it to FloatArray, and then ByteArray, but turn out it shows wrong waves.

**Comment by alxrm** [comment]
Well, you can try multiplying it by 128, but I'd better recommend not to use this library

**Comment by alxrm** [comment]
No reply — closing for now
