### ISSUE TITLE
sorry , i am  learner.  i can not use this libaray.  i need demo very much.   please help me

### ISSUE THREAD

**Issue by lmcjava** [alxrm/audiowave-progressbar#27]
i am sorry . my English is poor and i am learner.  please help me.  i need demo.  o(╥﹏╥)oo(╥﹏╥)o

**Comment by alxrm** [comment]
@lmcjava hey, there's a sample app code in the repo, here:

https://github.com/alxrm/audiowave-progressbar/tree/master/app

**Comment by lmcjava** [comment]
I can’t thank you enough. you are my god.
thank you , thank you , thank you... so much




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Alexey Derbyshev"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月18日(星期三) 下午5:53
收件人:&nbsp;"alxrm/audiowave-progressbar"<audiowave-progressbar@noreply.github.com&gt;;
抄送:&nbsp;"LEE"<960303980@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [alxrm/audiowave-progressbar] sorry , i am  learner.  i can not use this libaray.  i need demo very much.   please help me (#27)




@lmcjava hey, there's a sample app code in the repo, here:
 
https://github.com/alxrm/audiowave-progressbar/tree/master/app
