### ISSUE TITLE
Seek by user event

### ISSUE THREAD

**Issue by m-khademloo** [alxrm/audiowave-progressbar#4]
Thank for your library, it helps me a lot

but I can't catch the event of change progress value by user event,
I subscribe for setOnStopTracking and setOnProgressListener, but neither I can't catch that event. 

Is there a trick?

**Comment by alxrm** [comment]
@m-khademloo You have closed the issue, I assume you've figured out the solution, right?

**Comment by m-khademloo** [comment]
@alxrm Yeah :) Thanks for your responsibility
