### ISSUE TITLE
The waves doesn't match the sound?

### ISSUE THREAD

**Issue by tolgayavuz** [alxrm/audiowave-progressbar#6]
I'm getting bytes with this style;

`byte[] soundBytes = null;

                try {
                    InputStream inputStream =
                            getContentResolver().openInputStream(Uri.fromFile(new File(suanki_playlist.get(id).path)));

                    soundBytes = new byte[inputStream.available()];
                    soundBytes = toByteArray(inputStream);
                } catch (FileNotFoundException e) {
                    e.printStackTrace();
                } catch (IOException e) {
                    e.printStackTrace();
                }

                seekbar2.setRawData(soundBytes);`

Is it the problem?

**Comment by alxrm** [comment]
Seems okay, but I have 2 questions so far:

1) What is the size of yout file? (Asking because there is currently an issue with the files bigger than 10 mb and I'm too much of a lazy ass to fix it)
2) Are you sure your app has all permissions it needs? (Like `WRITE_EXTERNAL_STORAGE` or something like that)

**Comment by tolgayavuz** [comment]
My test file is 7.5 MB and yeah my app got the permission for WRITE_EXTERNAL_STORAGE, does it need more permissions for process?

**Comment by tolgayavuz** [comment]
Couple of screenshots for better understanding,

http://www.ucanhollandali.com/thedifference.jpg

edit: updated link

**Comment by alxrm** [comment]
I guess you're pointing towards the difference of the wave produced by this library and the proper one from SoundCloud, there's already an [issue](https://github.com/alxrm/audiowave-progressbar/issues/1) about it. _(Yeah, I haven't read the title of the issue)_

As a solution I offered there to use [another library](https://github.com/Semantive/waveform-android) which supports different music formats and was written by someone smarter than me, so consider using it

P. S. Right now I don't have that much time to add the support of all the popular music formats (like mp3, which has headers and some another compression-related crap inside it), sorry for that

**Comment by tolgayavuz** [comment]
Oh okay, thanks for the your time by the way your library is grea

**Comment by alxrm** [comment]
Thanks, I'll try to improve it some time
